package com.automateddocsys.pma.pmaclientdata.model;

// Generated May 10, 2015 12:25:20 AM by Hibernate Tools 3.6.0

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clientname generated by hbm2java
 */
@Entity
@Table(name = "clientname")
public class Clientname implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -34673684134908403L;
	@Id
	@Column(name = "ClientNo", unique = true, nullable = false, precision = 22, scale = 0)
	private Integer clientNo;
	@Column(name = "Name1")
	private String name1;
	@Column(name = "Name2")
	private String name2;
	@Column(name = "Name3")
	private String name3;
	@OneToMany(mappedBy="clientName",fetch=FetchType.EAGER)
	private List<Password> password;


	public Clientname() {
	}

	public Clientname(Integer clientNo) {
		this.clientNo = clientNo;
	}

	public Clientname(Integer clientNo, String name1, String name2, String name3) {
		this.clientNo = clientNo;
		this.name1 = name1;
		this.name2 = name2;
		this.name3 = name3;
	}

	public double getClientNo() {
		return this.clientNo;
	}

	public void setClientNo(Integer clientNo) {
		this.clientNo = clientNo;
	}

	public String getName1() {
		return this.name1;
	}

	public void setName1(String name1) {
		this.name1 = name1;
	}

	public String getName2() {
		return this.name2;
	}

	public void setName2(String name2) {
		this.name2 = name2;
	}

	public String getName3() {
		return this.name3;
	}

	public void setName3(String name3) {
		this.name3 = name3;
	}
	
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Clientname [clientNo=");
		builder.append(clientNo);
		builder.append(", ");
		if (name1 != null) {
			builder.append("name1=");
			builder.append(name1);
			builder.append(", ");
		}
		if (name2 != null) {
			builder.append("name2=");
			builder.append(name2);
			builder.append(", ");
		}
		if (name3 != null) {
			builder.append("name3=");
			builder.append(name3);
		}
		builder.append("]");
		return builder.toString();
	}

	public List<Password> getPassword() {
		return password;
	}

	public void setPassword(List<Password> password) {
		this.password = password;
	}

}
