package com.automateddocsys.pma.pmaclientdata.model;

// Generated May 10, 2015 12:25:20 AM by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Password generated by hbm2java
 */
@Entity
@Table(name = "passwords")
public class Password implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8502422661405683387L;
	/**
	 * 
	 */
	@Id
	@Column(name = "client_ID", unique = true, nullable = false)
	private Integer clientId;
	//private Integer clientNo;
	@Column(name = "Username", length = 25)
	private String username;
	@Column(name = "Password", length = 25)
	private String password;
	@Column(name = "Name", length = 100)
	private String name;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateAdded", length = 19)
	private Date dateAdded;
	
	@ManyToOne
	@JoinColumn(name="ClientNo", unique=true, nullable=false, updatable=false)
	private Clientname clientName;

	public Password() {
	}

	public Password(Integer clientId) {
		this.clientId = clientId;
	}

	public Password(int clientId, String username, String password, String name, Date dateAdded) {
		this.clientId = clientId;
		this.username = username;
		this.password = password;
		this.name = name;
		this.dateAdded = dateAdded;
	}

	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

//	@Column(name = "ClientNo")
//	public Integer getClientNo() {
//		return this.clientNo;
//	}
//
//	public void setClientNo(Integer clientNo) {
//		this.clientNo = clientNo;
//	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Password [clientId=");
		builder.append(clientId);
		builder.append(", username=");
		builder.append(username);
		builder.append(", password=");
		builder.append(password);
		builder.append(", name=");
		builder.append(name);
		builder.append(", dateAdded=");
		builder.append(dateAdded);
		builder.append(", clientName=");
		builder.append(clientName);
		builder.append("]");
		return builder.toString();
	}

	public Clientname getClientName() {
		return clientName;
	}

	public void setClientName(Clientname clientName) {
		this.clientName = clientName;
	}

}
