package com.automateddocsys.pma.pmaclientdata.model;

// Generated May 10, 2015 12:25:20 AM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Permissions generated by hbm2java
 */
@Entity
@Table(name = "permissions")
public class Permissions implements java.io.Serializable {

	private PermissionsId id;

	public Permissions() {
	}

	public Permissions(PermissionsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "validAccounts", column = @Column(name = "ValidAccounts")),
			@AttributeOverride(name = "portalAccounts", column = @Column(name = "PortalAccounts")) })
	public PermissionsId getId() {
		return this.id;
	}

	public void setId(PermissionsId id) {
		this.id = id;
	}

}
